# Enable AndroidX and Jetifier for dependency translation
android.useAndroidX=true
android.enableJetifier=true

# Optimizations
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Configure specific JDK 17 home because system default JDK 25 causes compilation errors
org.gradle.java.home=/Users/moeedmehmood/Library/Java/JavaVirtualMachines/ms-17.0.18-1/Contents/Home
